basePath: /
definitions:
  controller.BaseRes:
    properties:
      code:
        example: 0
        type: integer
      message:
        example: ok
        type: string
    type: object
  v1.CreateInstanceReqV1:
    properties:
      db_host:
        example: 10.10.10.10
        type: string
      db_password:
        example: "123456"
        type: string
      db_port:
        example: "3306"
        type: string
      db_user:
        example: root
        type: string
      desc:
        example: this is a test instance
        type: string
      instance_name:
        example: test
        type: string
      role_name_list:
        items:
          type: string
        type: array
      rule_template_name_list:
        items:
          type: string
        type: array
      workflow_template_name:
        type: string
    type: object
  v1.CreateRoleReqV1:
    properties:
      instance_name_list:
        items:
          type: string
        type: array
      role_desc:
        type: string
      role_name:
        type: string
      user_name_list:
        items:
          type: string
        type: array
    type: object
  v1.CreateUserReqV1:
    properties:
      email:
        example: test@email.com
        type: string
      role_name_list:
        items:
          type: string
        type: array
      user_name:
        example: test
        type: string
      user_password:
        example: "123456"
        type: string
    type: object
  v1.GetInstanceConnectableReqV1:
    properties:
      host:
        example: 10.10.10.10
        type: string
      password:
        example: "123456"
        type: string
      port:
        example: "3306"
        type: string
      user:
        example: root
        type: string
    type: object
  v1.GetInstanceConnectableResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/v1.InstanceConnectableResV1'
        type: object
      message:
        example: ok
        type: string
    type: object
  v1.GetInstanceResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/v1.InstanceResV1'
        type: object
      message:
        example: ok
        type: string
    type: object
  v1.GetInstanceSchemaResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/v1.InstanceSchemaResV1'
        type: object
      message:
        example: ok
        type: string
    type: object
  v1.GetInstanceTipsResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/v1.InstanceTipResV1'
        type: array
      message:
        example: ok
        type: string
    type: object
  v1.GetRoleTipsResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/v1.RoleTipResV1'
        type: array
      message:
        example: ok
        type: string
    type: object
  v1.GetRolesResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/v1.RoleResV1'
        type: array
      message:
        example: ok
        type: string
      total_nums:
        type: integer
    type: object
  v1.GetUserTipsResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/v1.UserTipResV1'
        type: array
      message:
        example: ok
        type: string
    type: object
  v1.GetUsersResV1:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/v1.UserResV1'
        type: array
      message:
        example: ok
        type: string
      total_nums:
        type: integer
    type: object
  v1.InstanceConnectableResV1:
    properties:
      is_instance_connectable:
        type: boolean
    type: object
  v1.InstanceResV1:
    properties:
      db_host:
        example: 10.10.10.10
        type: string
      db_port:
        example: "3306"
        type: string
      db_user:
        example: root
        type: string
      desc:
        example: this is a instance
        type: string
      instance_name:
        type: string
      role_name_list:
        items:
          type: string
        type: array
      rule_template_name_list:
        items:
          type: string
        type: array
      workflow_template_name:
        type: string
    type: object
  v1.InstanceSchemaResV1:
    properties:
      schema_name_list:
        items:
          type: string
        type: array
    type: object
  v1.InstanceTipResV1:
    properties:
      instance_name:
        type: string
    type: object
  v1.RoleResV1:
    properties:
      instance_name_list:
        items:
          type: string
        type: array
      role_desc:
        type: string
      role_name:
        type: string
      user_name_list:
        items:
          type: string
        type: array
    type: object
  v1.RoleTipResV1:
    properties:
      role_name:
        type: string
    type: object
  v1.UpdateInstanceReqV1:
    properties:
      db_host:
        example: 10.10.10.10
        type: string
      db_password:
        example: "123456"
        type: string
      db_port:
        example: "3306"
        type: string
      db_user:
        example: root
        type: string
      desc:
        example: this is a test instance
        type: string
      role_name_list:
        items:
          type: string
        type: array
      rule_template_name_list:
        example:
        - "1"
        items:
          type: string
        type: array
      workflow_template_name:
        type: string
    type: object
  v1.UpdateRoleReqV1:
    properties:
      instance_name_list:
        items:
          type: string
        type: array
      role_desc:
        type: string
      user_name_list:
        items:
          type: string
        type: array
    type: object
  v1.UpdateUserReqV1:
    properties:
      email:
        type: string
      role_name_list:
        items:
          type: string
        type: array
    type: object
  v1.UserLoginReq:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: test
        type: string
    type: object
  v1.UserLoginRes:
    properties:
      token:
        example: this is a jwt token string
        type: string
    type: object
  v1.UserResV1:
    properties:
      email:
        type: string
      role_name_list:
        items:
          type: string
        type: array
      user_name:
        type: string
    type: object
  v1.UserTipResV1:
    properties:
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for dev.
  license: {}
  title: Sqle API Docs
  version: "1.0"
paths:
  /v1/instance_connection:
    post:
      consumes:
      - application/json
      description: test instance db connection 注：可直接提交创建实例接口的body，该接口的json 内容是创建实例的
        json 的子集
      operationId: checkInstanceIsConnectableV1
      parameters:
      - description: instance info
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.GetInstanceConnectableReqV1'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetInstanceConnectableResV1'
      security:
      - ApiKeyAuth: []
      summary: 实例连通性测试（实例提交前）
      tags:
      - instance
  /v1/instance_tips:
    get:
      description: get instance tip list
      operationId: getInstanceTipListV1
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetInstanceTipsResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取实例提示列表
      tags:
      - instance
  /v1/instances:
    post:
      consumes:
      - application/json
      description: create a instance
      operationId: createInstanceV1
      parameters:
      - description: add instance
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.CreateInstanceReqV1'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 添加实例
      tags:
      - instance
  /v1/instances/{instance_name}/:
    delete:
      description: delete instance db
      operationId: deleteInstanceV1
      parameters:
      - description: instance name
        in: path
        name: instance_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 删除实例
      tags:
      - instance
    get:
      description: get instance db
      operationId: getInstanceV1
      parameters:
      - description: instance name
        in: path
        name: instance_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetInstanceResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取实例信息
      tags:
      - instance
    patch:
      description: update instance
      operationId: updateInstanceV1
      parameters:
      - description: instance name
        in: path
        name: instance_name
        required: true
        type: string
      - description: update instance request
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateInstanceReqV1'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 更新实例
      tags:
      - instance
  /v1/instances/{instance_name}/connection:
    get:
      description: test instance db connection
      operationId: checkInstanceIsConnectableByNameV1
      parameters:
      - description: instance name
        in: path
        name: instance_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetInstanceConnectableResV1'
      security:
      - ApiKeyAuth: []
      summary: 实例连通性测试（实例提交后）
      tags:
      - instance
  /v1/instances/{instance_name}/schemas:
    get:
      description: instance schema list
      operationId: getInstanceSchemasV1
      parameters:
      - description: instance name
        in: path
        name: instance_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetInstanceSchemaResV1'
      security:
      - ApiKeyAuth: []
      summary: 实例 Schema 列表
      tags:
      - instance
  /v1/login:
    post:
      description: user login
      operationId: loginV1
      parameters:
      - description: user login request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.UserLoginReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.UserLoginRes'
      summary: 用户登录
      tags:
      - user
  /v1/role_tips:
    get:
      description: get role tip list
      operationId: getRoleTipListV1
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetRoleTipsResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取角色提示列表
      tags:
      - role
  /v1/roles:
    get:
      consumes:
      - application/json
      description: get role list
      operationId: getRoleListV1
      parameters:
      - description: filter role name
        in: query
        name: filter_role_name
        type: string
      - description: filter user name
        in: query
        name: filter_user_name
        type: string
      - description: filter instance name
        in: query
        name: filter_instance_name
        type: string
      - description: page index
        in: query
        name: page_index
        type: integer
      - description: size of per page
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetRolesResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取角色列表
      tags:
      - role
    post:
      consumes:
      - application/json
      description: create role
      operationId: createRoleV1
      parameters:
      - description: create role
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.CreateRoleReqV1'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 创建角色
      tags:
      - role
  /v1/roles/{role_name}/:
    delete:
      consumes:
      - application/json
      description: delete role
      operationId: deleteRoleV1
      parameters:
      - description: role name
        in: path
        name: role_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - role
    patch:
      consumes:
      - application/json
      description: update role
      operationId: updateRoleV1
      parameters:
      - description: role name
        in: path
        name: role_name
        required: true
        type: string
      - description: update role request
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateRoleReqV1'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 更新角色信息
      tags:
      - role
  /v1/test:
    get:
      description: user login
      operationId: testV1
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: test
      tags:
      - user
  /v1/user_tips:
    get:
      description: get user tip list
      operationId: getUserTipListV1
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetUserTipsResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取用户提示列表
      tags:
      - user
  /v1/users:
    get:
      description: get user info list
      operationId: getUserListV1
      parameters:
      - description: filter user name
        in: query
        name: filter_user_name
        type: string
      - description: filter role name
        in: query
        name: filter_role_name
        type: string
      - description: page index
        in: query
        name: page_index
        type: integer
      - description: size of per page
        in: query
        name: page_size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetUsersResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息列表
      tags:
      - user
    post:
      consumes:
      - application/json
      description: create user
      operationId: createUserV1
      parameters:
      - description: create user
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.CreateUserReqV1'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 创建用户
      tags:
      - user
  /v1/users/{user_name}/:
    delete:
      description: delete user
      operationId: deleteUserV1
      parameters:
      - description: user name
        in: path
        name: user_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - user
    get:
      description: get user info
      operationId: getUserV1
      parameters:
      - description: user name
        in: path
        name: user_name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.UserResV1'
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - user
    patch:
      consumes:
      - application/json
      description: update user
      operationId: updateUserV1
      parameters:
      - description: user name
        in: path
        name: user_name
        required: true
        type: string
      - description: update user
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateUserReqV1'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
      security:
      - ApiKeyAuth: []
      summary: 更新用户信息
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
