basePath: /
definitions:
  controller.BaseRes:
    properties:
      code:
        example: 0
        type: integer
      message:
        example: ok
        type: string
    type: object
  controller.CreateInstanceReq:
    properties:
      db_type:
        description: mysql, mycat, sqlserver
        example: mysql
        type: string
      desc:
        example: this is a test instance
        type: string
      host:
        example: 10.10.10.10
        type: string
      name:
        example: test
        type: string
      password:
        example: "123456"
        type: string
      port:
        example: "3306"
        type: string
      rule_template_name_list:
        description: this a list for rule template name
        example:
        - template_1
        items:
          type: string
        type: array
      user:
        example: root
        type: string
    type: object
  controller.CreateTaskReq:
    properties:
      desc:
        example: this is a test task
        type: string
      inst_name:
        example: inst_1
        type: string
      name:
        example: test
        type: string
      schema:
        example: db1
        type: string
      sql:
        example: alter table tb1 drop columns c1
        type: string
    type: object
  controller.CreateTplReq:
    properties:
      desc:
        type: string
      name:
        type: string
      rule_name_list:
        example:
        - ddl_create_table_not_exist
        items:
          type: string
        type: array
    type: object
  controller.GetAllInstReq:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/model.Instance'
        type: array
      message:
        example: ok
        type: string
    type: object
  controller.GetAllRuleRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/model.Rule'
        type: array
      message:
        example: ok
        type: string
    type: object
  controller.GetAllSchemasData:
    properties:
      host:
        type: string
      name:
        type: string
      port:
        type: string
      schemas:
        items:
          type: string
        type: array
    type: object
  controller.GetAllSchemasRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/controller.GetAllSchemasData'
        type: array
      message:
        example: ok
        type: string
    type: object
  controller.GetAllTaskRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/model.Task'
        type: array
      message:
        example: ok
        type: string
    type: object
  controller.GetAllTplRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        items:
          $ref: '#/definitions/model.RuleTemplate'
        type: array
      message:
        example: ok
        type: string
    type: object
  controller.GetRuleTplRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/model.RuleTemplateDetail'
        type: object
      message:
        example: ok
        type: string
    type: object
  controller.GetSchemaRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        example:
        - db1
        items:
          type: string
        type: array
      message:
        example: ok
        type: string
    type: object
  controller.GetTaskRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/model.TaskDetail'
        type: object
      message:
        example: ok
        type: string
    type: object
  controller.InstanceRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        $ref: '#/definitions/model.InstanceDetail'
        type: object
      message:
        example: ok
        type: string
    type: object
  controller.PingInstRes:
    properties:
      code:
        example: 0
        type: integer
      data:
        description: 'true: ping success; false: ping failed'
        type: boolean
      message:
        example: ok
        type: string
    type: object
  model.CommitSql:
    properties:
      exec_result:
        type: string
      exec_status:
        type: string
      id:
        example: 1
        type: integer
      inspect_level:
        type: string
      inspect_result:
        type: string
      inspect_status:
        type: string
      number:
        type: integer
      sql:
        type: string
    type: object
  model.Instance:
    properties:
      db_type:
        example: mysql
        type: string
      desc:
        example: this is a instance
        type: string
      host:
        example: 10.10.10.10
        type: string
      id:
        example: 1
        type: integer
      name:
        type: string
      port:
        example: "3306"
        type: string
      user:
        example: root
        type: string
    type: object
  model.InstanceDetail:
    properties:
      db_type:
        example: mysql
        type: string
      desc:
        example: this is a instance
        type: string
      host:
        example: 10.10.10.10
        type: string
      id:
        example: 1
        type: integer
      name:
        type: string
      port:
        example: "3306"
        type: string
      rule_template_list:
        items:
          $ref: '#/definitions/model.RuleTemplate'
        type: array
      user:
        example: root
        type: string
    type: object
  model.RollbackSql:
    properties:
      exec_result:
        type: string
      exec_status:
        type: string
      id:
        example: 1
        type: integer
      number:
        type: integer
      sql:
        type: string
    type: object
  model.Rule:
    properties:
      desc:
        type: string
      level:
        description: notice, warn, error
        example: error
        type: string
      name:
        type: string
      value:
        type: string
    type: object
  model.RuleTemplate:
    properties:
      desc:
        type: string
      id:
        example: 1
        type: integer
      name:
        type: string
    type: object
  model.RuleTemplateDetail:
    properties:
      desc:
        type: string
      id:
        example: 1
        type: integer
      name:
        type: string
      rule_list:
        items:
          $ref: '#/definitions/model.Rule'
        type: array
    type: object
  model.Task:
    properties:
      desc:
        example: this is a task
        type: string
      id:
        example: 1
        type: integer
      instance_id:
        type: integer
      name:
        example: REQ201812578
        type: string
      schema:
        example: db1
        type: string
      sql:
        type: string
    type: object
  model.TaskDetail:
    properties:
      commit_sql_list:
        items:
          $ref: '#/definitions/model.CommitSql'
        type: array
      desc:
        example: this is a task
        type: string
      id:
        example: 1
        type: integer
      instance:
        $ref: '#/definitions/model.Instance'
        type: object
      instance_id:
        type: integer
      name:
        example: REQ201812578
        type: string
      rollback_sql_list:
        items:
          $ref: '#/definitions/model.RollbackSql'
        type: array
      schema:
        example: db1
        type: string
      sql:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: This is a sample server for dev.
  license: {}
  title: Sqle API Docs
  version: "1.0"
paths:
  /instances:
    get:
      description: get all instances
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetAllInstReq'
            type: object
      summary: 实例列表
    post:
      consumes:
      - application/json
      - application/json
      description: create a instance<br>create a instance
      parameters:
      - description: add instance
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/controller.CreateInstanceReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.InstanceRes'
            type: object
      summary: 添加实例
  /instances/{instance_id}/:
    delete:
      description: delete instance db
      parameters:
      - description: Instance ID
        in: path
        name: instance_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: 删除实例
    get:
      description: get instance db
      parameters:
      - description: Instance ID
        in: path
        name: instance_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.InstanceRes'
            type: object
      summary: 获取实例信息
    put:
      description: update instance db
      parameters:
      - description: Instance ID
        in: path
        name: instance_id
        required: true
        type: string
      - description: update instance
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/controller.CreateInstanceReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: 更新实例
  /instances/{instance_id}/connection:
    get:
      description: test instance db connection
      parameters:
      - description: Instance ID
        in: path
        name: instance_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.PingInstRes'
            type: object
      summary: 实例连通性测试
  /instances/{instance_id}/schemas:
    get:
      description: instance schema list
      parameters:
      - description: Instance ID
        in: path
        name: instance_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetSchemaRes'
            type: object
      summary: 实例 Schema 列表
  /rule_templates:
    get:
      description: get all rule template
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetAllTplRes'
            type: object
      summary: 规则模板列表
    post:
      consumes:
      - application/json
      - application/json
      description: create a rule template
      parameters:
      - description: add instance
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/controller.CreateTplReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: 添加规则模板
  /rule_templates/{template_id}/:
    delete:
      description: delete rule template
      parameters:
      - description: Template ID
        in: path
        name: template_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: 删除规则模板
    get:
      description: get rule template
      parameters:
      - description: Rule Template ID
        in: path
        name: template_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetRuleTplRes'
            type: object
      summary: 获取规则模板
    put:
      description: update rule template
      parameters:
      - description: Template ID
        in: path
        name: template_id
        required: true
        type: string
      - description: update rule template
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/controller.CreateTplReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: 更新规则模板
  /rules:
    get:
      description: get all rule template
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetAllRuleRes'
            type: object
      summary: 规则列表
  /schemas/:
    get:
      description: all schema list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetAllSchemasRes'
            type: object
      summary: 所有实例的 Schema 列表
  /tasks:
    get:
      description: get all tasks
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetAllTaskRes'
            type: object
      summary: Sql审核列表
    post:
      consumes:
      - application/json
      - application/json
      description: create a task
      parameters:
      - description: add task
        in: body
        name: instance
        required: true
        schema:
          $ref: '#/definitions/controller.CreateTaskReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetTaskRes'
            type: object
      summary: 创建Sql审核任务
  /tasks/{task_id}/:
    delete:
      description: delete task
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: 删除审核任务
    get:
      description: get task
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetTaskRes'
            type: object
      summary: 获取Sql审核任务信息
  /tasks/{task_id}/commit:
    post:
      description: commit sql
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: Sql提交上线
  /tasks/{task_id}/inspection:
    post:
      description: inspect sql
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetTaskRes'
            type: object
      summary: Sql提交审核
  /tasks/{task_id}/rollback:
    post:
      description: rollback sql
      parameters:
      - description: manual execute rollback sql
        in: query
        name: manual_execute
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.BaseRes'
            type: object
      summary: Sql提交回滚
swagger: "2.0"
